In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [9]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
ans = np.array([-8, 11, 3])
print(ans)

[-8 11  3]


In [16]:
print("augmented matrix:\n", np.vstack((A,ans)))

augmented matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-8 11  3]]


In [17]:
print(np.vstack((A,ans)).shape)

(4, 3)


In [20]:
def pivoting(A):
    for i in range(A.shape[0]): # col 
        for j in range(A.shape[1]): # row
            pivot = np.argmax(A[i]) #find largest pivot of each col
    

In [22]:
piv_A = pivoting(A)
print(piv_A)

[1 2 3 5 6 9]


In [ ]:
def Gauss_Jordan_Elimination(A):
    
            
                
    
    

In [25]:
list = [1, 2, 3]

In [26]:
list.pop(0)
print(list)

[2, 3]
