In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [8]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [9]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
ans = np.array([-8, 11, 3])
print(ans)

[-8 11  3]


In [3]:
import numpy as np
import tqdm as tqdm 

def gaussian_elimination_with_pivoting(A, b):
    n = len(A)
    # Main loop going through all columns
    for k in tqdm(range(n)):
        # Find the row with the maximum element in column k
        max_row = np.argmax(np.abs(A[k:n, k])) + k
        
        # Swap the current row with the row with the maximum element
        A[[k, max_row]] = A[[max_row, k]]
        b[[k, max_row]] = b[[max_row, k]]
        
        # Elimination process
        for row in range(k+1, n):
            factor = A[row, k] / A[k, k]
            A[row, k:] = A[row, k:] - factor * A[k, k:]
            b[row] = b[row] - factor * b[k]
    
    # Back substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
    return x, A


In [4]:
n = 50000  # Matrix size
low = -100  # Lower bound (inclusive)
high = 100  # Upper bound (exclusive)

A = np.random.randint(low, high, size=(n, n))
b = np.random.randint(low, high, size = n)

In [5]:
x, pivoted_A = gaussian_elimination_with_pivoting(A, b)

print("Solution x:", x)
print("Pivoted Matrix A after Gaussian Elimination: \n", pivoted_A)

TypeError: 'module' object is not callable. Did you mean: 'tqdm.tqdm(...)'?

In [20]:

def pivoting(A):
    sorted = np.zeros((A.shape[0], A.shape[1]))
    for i in range(A.shape[0]): # col 
        pivot = A[i][0] # find largest pivot of each col
        for j in range(A.shape[1]): # row
            if A[i][j] > pivot:
            A[][]
    return  

In [22]:
piv_A = pivoting(A)
print(piv_A)

[1 2 3 5 6 9]


In [ ]:
def Gauss_Jordan_Elimination(A):
    
            
                
    
    

In [25]:
list = [1, 2, 3]

In [26]:
list.pop(0)
print(list)

[2, 3]
